# Application name
spring.application.name=notification-service

# Server Port
server.port=8085

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka configuration
# Define the function (consumer)
spring.cloud.stream.function.definition=processMembershipEvent

# Connect to Kafka inside Docker
spring.cloud.stream.kafka.binder.brokers=localhost:9092
# Match producer topic
spring.cloud.stream.bindings.processMembershipEvent-in-0.destination=membership-topic
spring.cloud.stream.bindings.processMembershipEvent-in-0.group=membership-group
spring.cloud.stream.bindings.processMembershipEvent-in-0.content-type=application/json

# Ensure Kafka Consumer Uses JSON Deserializer
spring.cloud.stream.kafka.bindings.processMembershipEvent-in-0.consumer.configuration.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Java class to deserialize into
spring.cloud.stream.kafka.bindings.processMembershipEvent-in-0.consumer.configuration.spring.json.value.default.type=com.gym_management.notification_service.dto.MembershipEventDto

# Ensure the key is deserialized correctly
spring.cloud.stream.kafka.bindings.processMembershipEvent-in-0.consumer.configuration.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.stream.kafka.bindings.processMembershipEvent-in-0.consumer.configuration.spring.json.trusted.packages=*


# Email Configuration (Using Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smt.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/gym_notification
spring.data.mongodb.database=gym_notification
spring.data.mongodb.reactive.repositories.enabled=true